# Generated by Django 4.1 on 2023-03-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="用户名"),
                ),
                (
                    "password",
                    models.CharField(default="", max_length=255, verbose_name="密码"),
                ),
            ],
        ),
    ]
